apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
    spec:
      containers:
        - name: vault-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 40
            periodSeconds: 15
      volumes:
        {{- if .Values.persistence.hostPath }}
        - name: data-volume
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- else }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "vault-demo.name" . }}-pvc
        {{- end }}
