apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  namespace: demo
  labels:
    app.kubernetes.io/name: vault-agent-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-agent-injector
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: vault-agent-injector
          image: "hashicorp/vault-k8s:1.4.2"
          imagePullPolicy: IfNotPresent
          command: ["vault-k8s", "agent-injector", "-log-level=info"]
          env:
            - name: AGENT_INJECT_VAULT_ADDR
              value: "http://vault-demo.demo.svc:8200"
            - name: AGENT_INJECT_VAULT_AUTH_PATH
              value: "auth/kubernetes"
            - name: AGENT_INJECT_VAULT_ROLE
              value: "hana-role"
            - name: AGENT_INJECT_LOG_LEVEL
              value: "info"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-injector
  namespace: demo
spec:
  selector:
    app.kubernetes.io/name: vault-agent-injector
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-agent-injector-role
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-agent-injector-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-agent-injector-role
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: demo
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
webhooks:
  - name: vault.hashicorp.com
    clientConfig:
      service:
        name: vault-agent-injector
        namespace: demo
        path: "/mutate"
      caBundle: ""
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
