{{- if .Values.injector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault-agent-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-agent-injector
    spec:
      serviceAccountName: {{ .Values.injector.serviceAccount.name }}
      containers:
        - name: vault-agent-injector
          image: "{{ .Values.injector.image.repository }}:{{ .Values.injector.image.tag }}"
          imagePullPolicy: {{ .Values.injector.image.pullPolicy }}
          args:
            - "agent-inject"
            - "-log-level=info"
          env:
          {{- range .Values.injector.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.injector.resources | nindent 12 }}
{{- end }}
