apiVersion: v1
kind: Service
metadata:
  name: s4hanna
  labels:
    app: s4hanna
spec:
  type: ClusterIP
  selector:
    app: s4hanna
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432