apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s4hanna
  labels:
    app: s4hanna
spec:
  serviceName: s4hanna
  replicas: 1
  selector:
    matchLabels:
      app: s4hanna
  template:
    metadata:
      labels:
        app: s4hanna
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA 
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s4hanna-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}