apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-ads-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-ads-demo
  template:
    metadata:
      labels:
        app: java-ads-demo
    spec:
      containers:
      - name: java-ads-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.persistence.mountPath }}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "java-ads-demo.fullname" . }}-pvc
