apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-ads-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-ads-demo
  template:
    metadata:
      labels:
        app: java-ads-demo
    spec:
      containers:
      - name: java-ads-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080

        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.persistence.mountPath }}
          
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "java-ads-demo.name" . }}-pvc
