dockerhub_username: ryandevlab
hxe_image_name: hanaexpress
hxe_image_tag: latest
hxe_full_image: "{{ dockerhub_username }}/{{ hxe_image_name }}:{{ hxe_image_tag }}"

hxe_container_name: hxexsa1
hxe_hostname: hxehost
hxe_data_dir: /data/hxe
hxe_password_json_name: password.json
hxe_passwords:
  master: "HXEHana1"  # Must meet SAP complexity rules

# URL used in --passwords-url
passwords_url: "file:///hana/mounts/password.json"

published_ports:
  - "39013:39013"
  - "39017:39017"
  - "51000-51060:51000-51060"
  - "53075:53075"

container_sysctls:
  kernel.shmmax: "1073741824"
  net.ipv4.ip_local_port_range: "60000 65535"

container_ulimits:
  - "nofile=1048576:1048576"

passwords_url: "file:///hana/mounts/password.json"
sap_no_proxy: "localhost,127.0.0.1,hxehost,hxehost.localdomain"

# --- SAP HANA Express sysctl parameters ---
sysctl_params:
  fs.file-max: 20000000
  fs.aio-max-nr: 262144
  vm.memory_failure_early_kill: 1
  vm.max_map_count: 135217728
  net.ipv4.ip_local_port_range: "40000 60999"



