apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "s4hanna.fullname" . }}
  labels:
    app: {{ include "s4hanna.name" . }}
spec:
  serviceName: {{ include "s4hanna.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "s4hanna.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "s4hanna.name" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                name: s4hanna-secret
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "5Gi" }}
        storageClassName: {{ .Values.persistence.storageClass | default "default" }}