image:
  repository: aksdemoacr3.azurecr.io/sap4hanna
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5432

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: sap4hanna.mitechnology.org
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Optional: add TLS config if using cert-manager

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70    

env:
  - name: POSTGRES_PASSWORD
    value: "StrongPassword123"  

persistence:
  size: 5Gi
  storageClass: default