image:
  repository: aksdemoacr3.azurecr.io/dev/java-aks-demo
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: ""    

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: java4adobe.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70    
