image:
  repository: aksdemoacr3.azurecr.io/hello-world
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-world.ryandemolab.app
      paths:
        - path: /
          pathType: Exact
  tls: []  # Optional: add TLS config if using cert-manager  

service:
  type: ClusterIP
  port: 80