image:
  repository: aksdemoacr3.azurecr.io/hello-world
  tag: v1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-world.mitechnology.org
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Optional: add TLS config if using cert-manager  

service:
  type: LoadBalancer
  port: 80