apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ads-java-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-ads-demo
  template:
    metadata:
      labels:
        app: java-ads-demo
    spec:
      containers:
      - name: java-ads-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.persistence.mountPath }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.targetPort }}
        # livenessProbe:
        #   httpGet:
        #     path: /        # or /status
        #     port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "ads-java-chart.fullname" . }}-pvc