apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ads-java-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ads-java-demo
  template:
    metadata:
      labels:
        app: ads-java-demo
    spec:
      containers:
        - name: java-ads-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "java-ads-demo.fullname" . }}-pvc
        {{- end }}