apiVersion: v1
kind: Service
metadata:
  name: java-ads-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: java-ads-demo
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080