apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-db.name" . }}
  labels:
    app: {{ include "mysql-db.name" . }}
spec:
  serviceName: {{ include "mysql-db.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mysql-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql-db.name" . }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
