image:
  repository: ryandevlab/sap-hxe
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    db: 39017
    cockpit: 51000
  nodePorts:
    db: 30917
    cockpit: 31000

resources:
  requests:
    memory: 16Gi
    cpu: 4
  limits:
    memory: 24Gi
    cpu: 8

persistence:
  enabled: true
  accessMode: ReadWriteOnce   # still informative
  size: 50Gi                  # not used in hostPath, kept for clarity
  mountPath: /hana/data
  hostPath: /data/hana        # <— host path on your EC2 instance (must exist)

securityContext:
  fsGroup: 79
  runAsUser: 12000
  runAsGroup: 79

hana:
  hostname: hana-host
  healthcheckCommand: "pgrep -f hdbnameserver >/dev/null || exit 1"
  vault:
    secretPath: "kv/data/hana"
    secretKey: "master_password"
