image:
  repository: ryandevlab/mysql-demo
  tag: latest
  pullPolicy: Always

mysql:
  rootPassword: rootpass
  database: demodb
  user: demo
  password: demopass

service:
  type: NodePort
  port: 3306
  nodePort: 30306

persistence:
  size: 2Gi
  storageClass: ""
