{{- if not .Values.hana.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hana-password-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password.json: |
    {
      "master_password": "{{ .Values.hana.masterPassword }}"
    }
{{- end }}
