apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sap-hana.name" . }}
  labels:
    app: {{ include "sap-hana.name" . }}
spec:
  serviceName: {{ include "sap-hana.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sap-hana.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sap-hana.name" . }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "hana-role"
        vault.hashicorp.com/agent-inject-secret-password.json: "{{ .Values.hana.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-password.json: |
          {{`{{- with secret "`}}{{ .Values.hana.vault.secretPath }}{{`" -}}`}}
          {
            "master_password": "{{`{{ .Data.data.`}}{{ .Values.hana.vault.secretKey }}{{` }}`}}"
          }
          {{`{{- end }}`}}
    spec:
      serviceAccountName: vault-auth
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: sap-hana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.db }}
            - containerPort: {{ .Values.service.ports.cockpit }}
          args:
            [
              "--agree-to-sap-license",
              "--passwords-url", "file:///vault/secrets/password.json",
              "--dont-check-system",
              "--dont-check-mount-points"
            ]
          securityContext:
            privileged: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
          volumeMounts:
            - name: hana-storage
              mountPath: {{ .Values.persistence.mountPath }}
          livenessProbe:
            exec:
              command: ["/bin/bash", "-c", "{{ .Values.hana.healthcheckCommand }}"]
            initialDelaySeconds: 180
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: hana-storage
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
